# Generated by Django 3.2 on 2021-05-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoclips',
            old_name='video',
            new_name='video_clip',
        ),
        migrations.AddField(
            model_name='videos',
            name='sliced',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
