# Generated by Django 3.2 on 2021-05-07 10:09

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_video_clip_videoclips_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=api.models.Videos.thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='videos',
            name='atChild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.antypicalchild'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='tChild',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.typicalchild'),
        ),
    ]
