# Generated by Django 3.2 on 2021-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210507_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
