# Generated by Django 3.2 on 2021-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_videos_thumbnail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclips',
            name='video',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
