# Generated by Django 3.2 on 2021-05-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_videoclips_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclips',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
