# Generated by Django 3.2 on 2021-05-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_videoclips_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclips',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
