# Generated by Django 3.2 on 2021-05-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_videoclips_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclips',
            name='file_extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoclips',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
